server:
  port: 13000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

security:
    basic:
        enabled: false


payu:
  client:
    posId: 145227
    secondKey: 13a980d4f851f3d9a1cfc792fb1f5e50
    clientSecret: 12f071174cb7eb79d4aac5bc2f07563f
    accessTokenUri: https://secure.payu.com/pl/standard/user/oauth/authorize
    authorizationUri: https://secure.payu.com/pl/standard/user/oauth/authorize
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    baseResourceUri: https://secure.payu.com/

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
